/*
  This file was autogenerated by raw2c.
Visit http://www.devkitpro.org
*/

//---------------------------------------------------------------------------------
#ifndef _button_click2_sound_h_
#define _button_click2_sound_h_
//---------------------------------------------------------------------------------
extern unsigned char button_click2_sound[];
extern const int button_click2_sound_size;
//---------------------------------------------------------------------------------
#endif //_button_click2_sound_h_
//---------------------------------------------------------------------------------
