/*
  This file was autogenerated by raw2c.
Visit http://www.devkitpro.org
*/

//---------------------------------------------------------------------------------
#ifndef _erase_sound_h_
#define _erase_sound_h_
//---------------------------------------------------------------------------------
extern unsigned char erase_sound[];
extern const int erase_sound_size;
//---------------------------------------------------------------------------------
#endif //_erase_sound_h_
//---------------------------------------------------------------------------------
