/*
  This file was autogenerated by raw2c.
Visit http://www.devkitpro.org
*/

//---------------------------------------------------------------------------------
#ifndef _hoverkey_sound_h_
#define _hoverkey_sound_h_
//---------------------------------------------------------------------------------
extern unsigned char hoverkey_sound[];
extern const int hoverkey_sound_size;
//---------------------------------------------------------------------------------
#endif //_hoverkey_sound_h_
//---------------------------------------------------------------------------------
