/*
  This file was autogenerated by raw2c.
Visit http://www.devkitpro.org
*/

//---------------------------------------------------------------------------------
#ifndef _maxkey_sound_h_
#define _maxkey_sound_h_
//---------------------------------------------------------------------------------
extern unsigned char maxkey_sound[];
extern const int maxkey_sound_size;
//---------------------------------------------------------------------------------
#endif //_maxkey_sound_h_
//---------------------------------------------------------------------------------
