/*
  This file was autogenerated by raw2c.
Visit http://www.devkitpro.org
*/

//---------------------------------------------------------------------------------
#ifndef _presskey_sound_h_
#define _presskey_sound_h_
//---------------------------------------------------------------------------------
extern unsigned char presskey_sound[];
extern const int presskey_sound_size;
//---------------------------------------------------------------------------------
#endif //_presskey_sound_h_
//---------------------------------------------------------------------------------
