/*
  This file was autogenerated by raw2c.
Visit http://www.devkitpro.org
*/

//---------------------------------------------------------------------------------
#ifndef _selectbutton_sound_h_
#define _selectbutton_sound_h_
//---------------------------------------------------------------------------------
extern unsigned char selectbutton_sound[];
extern const int selectbutton_sound_size;
//---------------------------------------------------------------------------------
#endif //_selectbutton_sound_h_
//---------------------------------------------------------------------------------
